[2023-06-15T20:17:23.929+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:16:58+00:00 [queued]>
[2023-06-15T20:17:23.954+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:16:58+00:00 [queued]>
[2023-06-15T20:17:23.954+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T20:17:23.966+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 13:16:58+00:00
[2023-06-15T20:17:23.969+0700] {standard_task_runner.py:57} INFO - Started process 71743 to run task
[2023-06-15T20:17:23.975+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T13:16:58+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmppwx7q37z']
[2023-06-15T20:17:23.977+0700] {standard_task_runner.py:85} INFO - Job 86: Subtask upload_to_github
[2023-06-15T20:17:24.020+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:16:58+00:00 [running]> on host macbook-pro.local
[2023-06-15T20:17:24.064+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T13:16:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T13:16:58+00:00'
[2023-06-15T20:22:10.550+0700] {process_utils.py:131} INFO - Sending 15 to group 71743. PIDs of all processes in the group: [71743]
[2023-06-15T20:22:10.550+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 71743
[2023-06-15T20:23:10.581+0700] {process_utils.py:149} WARNING - process psutil.Process(pid=71743, name='Python', status='running', started='20:17:23') did not respond to SIGTERM. Trying SIGKILL
[2023-06-15T20:23:10.600+0700] {process_utils.py:86} INFO - Sending the signal 9 to group 71743
[2023-06-15T20:23:10.608+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=71743, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:17:23') (71743) terminated with exit code -9
[2023-06-15T20:23:10.609+0700] {standard_task_runner.py:172} ERROR - Job 86 was killed before it finished (likely due to running out of memory)
