[2023-06-16T11:31:07.111+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-16T04:30:33+00:00 [queued]>
[2023-06-16T11:31:07.121+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-16T04:30:33+00:00 [queued]>
[2023-06-16T11:31:07.121+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-16T11:31:07.138+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-16 04:30:33+00:00
[2023-06-16T11:31:07.141+0700] {standard_task_runner.py:57} INFO - Started process 92629 to run task
[2023-06-16T11:31:07.150+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-16T04:30:33+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpk0mnjrxi']
[2023-06-16T11:31:07.154+0700] {standard_task_runner.py:85} INFO - Job 226: Subtask upload_to_github
[2023-06-16T11:31:07.216+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-16T04:30:33+00:00 [running]> on host macbook-pro.local
[2023-06-16T11:31:07.295+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T04:30:33+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-16T04:30:33+00:00'
[2023-06-16T11:31:07.311+0700] {mainflow.py:48} INFO - {'AUTHENTICATION': {'TOKEN': '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', 'USERNAME': 'nxquang-al'}, 'MESSAGE': 'test-github-access-token', 'REPOSITORY': {'BRANCH': 'main', 'NAME': 'Test-github-api', 'OWNER': 'R2th'}}
[2023-06-16T11:31:07.311+0700] {mainflow.py:49} INFO - /Users/lap14202/.airflow/data/Requirements.rst
[2023-06-16T11:31:07.312+0700] {upload_to_github.py:21} INFO - /repos/R2th/Test-github-api/contents/Users/lap14202/.airflow/data/Requirements.rst
[2023-06-16T11:31:07.313+0700] {upload_to_github.py:22} INFO - {'Authorization': 'Bearer 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', 'Content-Type': 'application/vnd.github+json'}
[2023-06-16T11:31:07.313+0700] {upload_to_github.py:23} INFO - main
[2023-06-16T11:31:07.439+0700] {upload_to_github.py:40} INFO - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
[2023-06-16T11:31:07.440+0700] {upload_to_github.py:41} INFO - Retrieve SHA fail!
[2023-06-16T11:31:07.441+0700] {python.py:183} INFO - Done. Returned value was: None
[2023-06-16T11:31:07.448+0700] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=thethree_reqif_to_rst, task_id=upload_to_github, execution_date=20230616T043033, start_date=20230616T043107, end_date=20230616T043107
[2023-06-16T11:31:07.488+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-16T11:31:07.510+0700] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
