[2023-06-15T20:00:21.105+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T12:59:39+00:00 [queued]>
[2023-06-15T20:00:21.116+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T12:59:39+00:00 [queued]>
[2023-06-15T20:00:21.116+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T20:00:21.141+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 12:59:39+00:00
[2023-06-15T20:00:21.145+0700] {standard_task_runner.py:57} INFO - Started process 68027 to run task
[2023-06-15T20:00:21.157+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T12:59:39+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpiekcilvr']
[2023-06-15T20:00:21.160+0700] {standard_task_runner.py:85} INFO - Job 78: Subtask upload_to_github
[2023-06-15T20:00:21.276+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T12:59:39+00:00 [running]> on host macbook-pro.local
[2023-06-15T20:00:21.480+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T12:59:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T12:59:39+00:00'
[2023-06-15T20:04:42.788+0700] {process_utils.py:131} INFO - Sending 15 to group 68027. PIDs of all processes in the group: [68027]
[2023-06-15T20:04:42.788+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 68027
[2023-06-15T20:05:42.794+0700] {process_utils.py:149} WARNING - process psutil.Process(pid=68027, name='Python', status='running', started='20:00:21') did not respond to SIGTERM. Trying SIGKILL
[2023-06-15T20:05:42.797+0700] {process_utils.py:86} INFO - Sending the signal 9 to group 68027
[2023-06-15T20:05:42.813+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=68027, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:00:21') (68027) terminated with exit code -9
[2023-06-15T20:05:42.814+0700] {standard_task_runner.py:172} ERROR - Job 78 was killed before it finished (likely due to running out of memory)
